projects:
  app:
    schemaPath: "schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4444"
  prisma:
    schemaPath: "generated/prisma-schema.graphql"
    extensions:
      prisma: prisma.yml
